name: Playwright Tests with Stages

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: write
  issues: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install chromium

      - name: Run Playwright tests
        run: npx playwright test

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/

  generate-report:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Allure CLI
        run: npm install -g allure-commandline

      - name: Download Playwright report
        uses: actions/download-artifact@v4
        with:
          name: playwright-report

      - name: Generate Allure report
        run: |
          mkdir -p allure-results
          allure generate allure-results --clean -o allure-report

      - name: Debug Allure Results
        run: |
          echo "Listing allure-results directory:"
          ls -l allure-results

      - name: Debug Allure Report Generation
        run: |
          echo "Listing allure-report directory:"
          ls -l allure-report

      - name: Upload Allure report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: ${{ github.workspace }}/allure-report

  deploy:
    needs: generate-report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: gh-pages

      - name: Download Allure report
        uses: actions/download-artifact@v4
        with:
          name: allure-report

      - name: Debug Artifact Download
        run: |
          echo "Listing downloaded artifact contents:"
          ls -l allure-report

      - name: Check for Allure Report
        run: |
          if [ ! -d "allure-report" ]; then
            echo "Allure report directory is missing!"
            exit 1
          fi

      - name: Set unique path for report
        run: |
          echo "REPORT_PATH=reports/${{ github.run_id }}" >> $GITHUB_ENV

      - name: Move Allure report to unique path
        run: |
          mkdir -p ${{ env.REPORT_PATH }}
          cp -r allure-report/* ${{ env.REPORT_PATH }}/

      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
          dest_dir: ${{ env.REPORT_PATH }}

      - name: Display the deployed URL
        run: |
          echo "::notice ::Deployed Report URL: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/reports/${{ github.run_id }}"