name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: write
  issues: write

jobs:
  testExecutionandReporting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Allure CLI
        run: npm install -g allure-commandline
      - name: Install Playwright Browsers
        run: npx playwright install chromium
      - name: Run Playwright tests
        run: npx playwright test .tests/githubIntegration.spec.js
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: Generate Allure report
        run: |
          mkdir -p allure-results
          allure generate allure-results --clean -o allure-report
      - name: Upload Allure report
        if: always() # Ensure the report is uploaded even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report/
      - name: Set unique path for report
        run: |
          echo "REPORT_PATH=reports/${{ github.run_id }}" >> $GITHUB_ENV
      - name: Move Allure report to unique path
        run: |
          mkdir -p ${{ env.REPORT_PATH }}
          cp -r allure-report/* ${{ env.REPORT_PATH }}/
      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
          destination_dir: ${{ env.REPORT_PATH }}
      - name: Display the deployed URL
        run: |
          echo "::notice ::Deployed Report URL: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/reports/${{ github.run_id }}"